services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - fuel-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - fuel-stations-management-system-app:latest
    ports:
      - "3000:3000"
      - "5556:5556"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fuel_stations
      - NEXTAUTH_URL=http://localhost
      - NEXTAUTH_SECRET=R/XsCFWXqVbqR/6YX7Vj73KQsO4Pco7YdbPzuDZ2FH4=
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - fuel-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fuel_stations
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fuel-network

networks:
  fuel-network:
    driver: bridge

volumes:
  postgres_data:
  nginx_cache:
  nginx_logs:
