services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fuel_stations
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=R/XsCFWXqVbqR/6YX7Vj73KQsO4Pco7YdbPzuDZ2FH4=
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - fuel-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fuel_stations
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fuel-network

networks:
  fuel-network:
    driver: bridge

volumes:
  postgres_data:
